name: Tege Desktop
on:
  push:
    branches: [ "main" ]
    
env: 
  PROJECT_PATH: NoteApp/NoteTakingApp/NoteTakingApp.csproj

permissions:
  id-token: write
  contents: read

jobs:
  deploy: 
    runs-on: windows-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet clean NoteApp/NoteTakingApp.IntegrationTest
      - run: dotnet build NoteApp/NoteTakingApp.IntegrationTest
      - run: dotnet test NoteApp/NoteTakingApp.IntegrationTest
      - run: dotnet build ${{env.PROJECT_PATH}} -c Release 
      - run: dotnet publish NoteApp/NoteTakingApp/NoteTakingApp.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --output NoteApp/Publish 
      - run: ls NoteApp/Publish
      - name: Release with release-please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          token: ${{ secrets.PAT }} 
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} D:/a/Tege/Tege/NoteApp/Publish/NoteTakingApp.exe

