name: Tege Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env: 
  PROJECT_PATH: NoteApp/NoteTakingApp/NoteTakingApp.csproj

jobs:
  deploy: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore ${{env.PROJECT_PATH}}

      - run: dotnet build ${{env.PROJECT_PATH}} -c Release --no-restore

      - run: dotnet publish NoteApp/NoteTakingApp/NoteTakingApp.csproj -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build
          
      - uses: actions/upload-artifact@v2
        with:
          name: Tege
          path: NoteTakingApp/bin/Release/net8.0-windows/win-x64/publish/NoteTakingApp.exe
          
