name: Tege Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env: 
  PROJECT_PATH: NoteApp/NoteTakingApp/NoteTakingApp.csproj

jobs:
  deploy: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore ${{env.PROJECT_PATH}}

      - run: dotnet build ${{env.PROJECT_PATH}} -c Release --no-restore

      - run: dotnet publish ${{env.PROJECT_PATH}} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: 1.1.beta
          release_name: Tege.1.1.beta

      - uses: csexton/release-asset-actions@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          pattern: NoteApp/NoteTakingApp/bin/Release/net8.0-windows/win-x64/publish/*.exe
          release-url: ${{steps.create_release.outputs.upload_url}}
        
