name: Tege Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env: 
  PROJECT_PATH: NoteApp/NoteTakingApp/NoteTakingApp.csproj

jobs:
  deploy: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet build ${{env.PROJECT_PATH}} -c Release --no-restore

      - run: dotnet publish NoteApp/NoteTakingApp/NoteTakingApp.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --output NoteApp/Publish 
     
      - name: Get tag name from ref
        shell: bash
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
        id: get_tag
      - name: Create tag in public repository
        run: |
          cd ${{github.workspace}}/another_public_repo
          git tag ${{ steps.get_tag.outputs.tag }}
          git push --tags --porcelain
      
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: TeGe ${{ steps.get_tag.outputs.tag }}

      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: NoteApp/Publish/*.exe
          release-url: ${{ steps.create_release.outputs.upload_url }}
