name: Tege Desktop
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env: 
  PROJECT_PATH: NoteApp/NoteTakingApp/NoteTakingApp.csproj

jobs:
  deploy: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet build ${{env.PROJECT_PATH}} -c Release 

      - run: dotnet publish NoteApp/NoteTakingApp/NoteTakingApp.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --output NoteApp/Publish 

      - name: Release with release-please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} 
        
